# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python.<br>

_**<font color=green>Why is it so important for Data Science with Python?</font>**_

- Numpy is incredibly fast, as it has bindings to C libraries

- Almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks

__*[numpy](http://www.numpy.org/)*__ is the core library for scientific computing in Python. 

It provides a high-performance multidimensional array object, as well as tools for working with these arrays. 

If you are already familiar with MATLAB, you might find *[this tutorial useful](http://wiki.scipy.org/NumPy_for_Matlab_Users)* to get started with Numpy.

For more info on why you would want to use Arrays instead of lists, [check out this great StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy in this notebook. And to get started, we need to install it!

## Installation Instructions

It is **_highly recommended_** you install Python using the [Anaconda distribution](https://anaconda.org) to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install.

If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:
    
    conda install numpy
    
If you do not have Anaconda and can not install it, **please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library: 

`import numpy as np`

In [1]:
import numpy as np

NumPy has many built-in functions and capabilities. In this notebook we will focus on some of the most important aspects of NumPy:
- vectors
- arrays
- matrices
- number generation

Let's start by discussing basic arrays.

# Arrays

NumPy arrays are the main way we will use NumPy throughout the course. 

NumPy arrays essentially come in two flavors:
- vectors 
- matrices

**Vectors** are strictly 1-d arrays. (like a list)

**Matrices** are 2-d (but you should note a matrix can still have only one row or one column).

A numpy *array* is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

-  __rank:__ The number of rows in the array
-  __shape:__ tuple of integers giving the size of the array along each dimension


## Creating NumPy Arrays

We can initialize NumPy arrays from nested Python lists, and access elements using square brackets.

You can read about other methods (than those listed below) of array creation [in the documentation](http://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation).

### From a Python List

We can create an array by directly converting a list or list of lists.

**ACTION STEPS:**
<div class="alert alert-block alert-success">
1. Return the value of **int_list**:  a list of integers [1, 4)<br>
2. Create an array called **arr1** from that list:  `np.array(your_list)`<br>
3. Show the type(**arr1**)<br>
4. Show element 2 of **arr1**<br>
5. Create **my_matrix** - a 3 element list where each element is made of 3 INTs<br>
6. Create an array from **my_matrix** (see number 2 above)</div>

In [3]:
int_list = [1,2,3]
int_list

[1, 2, 3]

In [4]:
arr1 = np.array(int_list)
arr1

array([1, 2, 3])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1[2]

3

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [10]:
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## For Multiple Array (Matrix)

`np.array(list)[row]` == `var[row]`

`np.array(list)[row][col]` == `np.array(list)[row, col]`

Action Steps:
<div class="alert alert-block alert-success">
1. Create a variable **arr_shape2** and create an np.array like:<br>
    | 1 | 2 | 3 |<br>
    | 4 | 5 | 6 |<br>
2. Provide **arr_shape2**'s shape<br>
3. Provide **arr_shape2**'s type<br>
4. Show element 1 of **arr_shape2**<br>
5. Show element 1, column 2 of **arr_shape2**</div>

<div class="alert alert-block alert-warning">**Thoughts to Ponder:**<br>
1. What other way could you do 5?</div>

In [13]:
arr_shape2 = np.array([[1,2,3], [4,5,6]])
print(arr_shape2)
x=1

[[1 2 3]
 [4 5 6]]


In [14]:
arr_shape2.shape

(2, 3)

In [15]:
type(arr_shape2)

numpy.ndarray

In [16]:
arr_shape2[1]

array([4, 5, 6])

In [19]:
print(arr_shape2[1,2])
print(arr_shape2[1][2])

6
6


### zeros ones

This section will explain how to generate arrays of zeros.

This is for a **numpy** rank 1 of `int1` zeros:

`np.zeros(int1)`

This is for a **numpy** rank `int1` of `int2` zeros:

`np.zeros((int1, int2))`

This takes in 2 options for the first & only argument.
1. INTEGER - will create an array of 1 row, INT columns
2. TUPLE - will create an array of (row, col)

**ACTION PLAN:**
<div class="alert alert block alert-success">
1. Create a **numpy** array of rank 1 of 3 zeros<br>
2. Create a **numpy** array of rank 4 of 8 zeros<br</div>

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.zeros((4,8))
#np.zeros((768,1024))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### ones

This section will explain how to generate arrays of zeros or ones.

This is for a **numpy** rank 1 of `int1` ones:

`np.ones(int1)`

This is for a **numpy** rank `int1` of `int2` ones:

`np.ones((int1, int2))`

**ACTION PLAN:**
<div class="alert alert block alert-success">
1. Create a **numpy** array of rank 1 of 3 ones<br>
2. Create a **numpy** array of rank 3 of 3 ones</div>

In [26]:
np.ones(3)

array([1., 1., 1.])

In [30]:
np.ones((3,3),np.float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Create A Constant Array

If you're looking to create an array full of any number, simply call the **_full()_** function on *numpy* as follows:

`np.full((row, col), int_or_float)`

**ACTION STEPS:**
<div class="alert alert-block alert-success">
1. Create a constant array of 5 rows, 8 columns with 1 as the 2nd input parameter.<br>
2. Create a constant array of 8 rows, 5 columns with 1.75 as the 2nd input parameter.</div>

In [31]:
np.full((5,8), 1)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [32]:
np.full((8,5), 1.75)

array([[1.75, 1.75, 1.75, 1.75, 1.75],
       [1.75, 1.75, 1.75, 1.75, 1.75],
       [1.75, 1.75, 1.75, 1.75, 1.75],
       [1.75, 1.75, 1.75, 1.75, 1.75],
       [1.75, 1.75, 1.75, 1.75, 1.75],
       [1.75, 1.75, 1.75, 1.75, 1.75],
       [1.75, 1.75, 1.75, 1.75, 1.75],
       [1.75, 1.75, 1.75, 1.75, 1.75]])

### linspace
Return evenly spaced numbers over a specified interval.

`np.linspace(float1, float2, float3)`

- float1:  starting float
- float2:  ending float
- float3:  number of elements requested back

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Create an array of 6 evenly spaced numbers from 0 up to and including 42<br>
2. Create an array of 50 evenly spaced numbers from 0 up to and including 10<br>
3. Show the shape of both</div>

In [33]:
np.linspace(0,42, 6)

array([ 0. ,  8.4, 16.8, 25.2, 33.6, 42. ])

In [34]:
np.linspace(0,10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [35]:
print(np.linspace(0,42, 6).shape)
print(np.linspace(0,10, 50).shape)

(6,)
(50,)


## eye

Creates an identity matrix.

`np.eye(int1)`

The INT required input parameter tells how many columns/rows it should create to make a square and fill in the diagonal.

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Create a 4 by 4 identity matrix</div>

In [36]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

NumPy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

`np.random.rand(int1)` 

Creates a vector array of int1 elements with shape (`int1`, ) using random numbers.

`np.random.rand(int1, int2)` 

Creates a matrix with shape (int1, int2) using random data

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Create a random array of rank 1 with 2 elements<br>
2. Create a random 5 by 5 matrix</div>

In [42]:
np.random.rand(1,2)

array([[0.22209732, 0.72612367]])

In [43]:
np.random.rand(5,5)

array([[2.35095432e-01, 5.54011308e-01, 5.75371025e-01, 2.11456462e-01,
        7.70406969e-01],
       [5.15022384e-01, 9.37481067e-01, 3.17717476e-01, 5.10266331e-01,
        8.42220217e-01],
       [7.43545535e-02, 6.07850021e-01, 7.89549899e-01, 3.53022389e-01,
        6.55373650e-04],
       [9.26790913e-01, 6.73786537e-01, 7.18795058e-01, 9.06368234e-01,
        3.16696952e-01],
       [4.67208055e-01, 4.83062546e-01, 8.42404189e-01, 2.17196462e-01,
        7.84439390e-01]])

### randn

Return a sample (or samples) from the "standard normal" distribution - unlike rand which is uniform.

<div class="alert alert-block alert-info">This can include negative floats unlike **rand** function.</div>

`np.random.randn(int1)`

Creates an array with shape (int1, ) filled with samples from the "standard normal" deviation.

`np.random.randn(int1, int2)`

Creates an array with shape (int1, int2) filled with samples from the "standard normal" deviation.

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Create a vector array of 2 samples of "standard normal" distribution<br>
2. Create a 5 by 5 matrix array of "standard normal" distribution</div>

In [44]:
np.random.randn(2)

array([0.0142257 , 1.11499125])

In [45]:
np.random.randn(5,5)

array([[-0.34654538,  0.91213074,  0.79762076,  1.51637536,  0.8098395 ],
       [ 0.21600932,  0.4121488 ,  0.06432961, -0.35175271,  0.76319984],
       [ 0.35537491,  0.36646089, -1.96673804,  1.23707713,  2.24947235],
       [ 0.74714328, -0.74615919, -0.94895424,  0.59668291, -0.8184049 ],
       [-0.58090157,  0.35379032,  1.30635992, -2.07320481, -0.32296673]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

`np.random.randint(int1, int2, int3)`

If int3 is not provided, this command will return a single INT. Otherwise, an array of shape (`int3`, ) will be returned.

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Return a random integer from 1 up to but not including 100<br>
2. Create a vector array of 10 random integers from 1 to 100 exclusive</div>

In [48]:
np.random.randint(1,100)

94

In [51]:
np.random.randint(0,100, 10)

array([42, 21, 80, 40, 88, 59, 37, 99, 35,  0])

# Array Attributes and Methods

There are many built-in ways to generate Arrays - here are a few most common ones.

## arange

`np.arange(int1, int2, int3)`

Provides an array of `int3` elements from `start_int` to `stop_int`.

`np.arange(0, stop_int)` === `np.arnage(stop_int)`

Provides an array of shape (int1, ) filled with integers starting from 0 up to but not including int1.

- **1st argument:**  starting point
- **2nd argument:**  up to and **not including** point
- **3rd argument:**  preferred spacing

<div class="alert alert-block alert-info">**NOTE:** If None (or nothing provided) for 3rd argument it will default to 1</div>

**ACTION STEPS:**
<div class="alert alert-block alert-success">
1. Create a range of INTs from 0 to 25 & assign to **arr**<br>
2. Create a range of INTs from 0 to 11 with a step of 2</div>

In [53]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
#print(np.linspace(0,12,7))
print(np.arange(0,11,2))

[ 0  2  4  6  8 10]


## dtype

You can also grab the data type of the object in the array.

`var.dtype`

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Call the dtype attribute for **arr**</div>

In [59]:
type(arr)
arr.shape
arr.dtype

dtype('int32')

## max,min,argmax,argmin

These are useful methods for finding max or min values.
<br>... Or to find their index locations using argmin or argmax.

`var.max()`

Returns the max value in the array.

`var.argmax()`

Returns the location (index) of the max value within the array.

`var.min()`

Returns the min value in the array

`var.argmin()`

Returns the location (index) of the min value within the array.

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Assign **arr** the creation of an array of 25 random values of standard deviation<br>
2. Find the max of **arr**<br>
3. Find the index of the max of **arr**<br>
4. Find the min of **arr**<br>
5. Find the index of min of **arr**</div>

In [63]:
arr =  np.random.randn(25)
arr

array([-0.88241182, -0.42854637, -1.16310469, -0.63880992, -1.19410077,
       -0.6832738 , -0.68615558, -0.14458476, -1.59410106, -0.3934634 ,
       -0.19794046,  0.34840901, -1.81800176,  0.91827835,  2.57183525,
        0.2225418 ,  1.59975007, -0.49670532, -0.88890396, -1.03514511,
       -0.35399532,  0.10708129, -0.05042042, -0.42401613,  0.55496822])

In [64]:
arr.max()

2.5718352464275203

In [65]:
arr.argmax()

14

In [66]:
arr.min()

-1.8180017620807027

In [67]:
arr.argmin()

12

# Shape

Shape is an attribute that arrays have (not a method).

`var.shape`

Creates a **vector** and returns a 2 element tuple:  *(columns, rows)*

#### For Single Array (Vector)

Action Steps:
<div class="alert alert-block alert-success">
1. Create a variable **arr_shape1** and assign it the value of an np.array() with 3 INTs & show result<br>
2. Provide **arr_shape1**'s shape<br>
3. Provide **arr_shape1**'s type<br>
4. Show element 2 of **arr_shape1**</div>

In [69]:
arr_shape1 = np.array([1,2,3])

In [70]:
arr_shape1.shape

(3,)

In [73]:
# type(arr_shape1.shape) # tuple
type(arr_shape1)

numpy.ndarray

In [74]:
arr_shape1[2]

3

## Reshape
Returns an array containing the same data with a new shape.

`var.reshape(int1, int2)`

Where **var** is some variable created for an array of shape `(int1, int2)`

<div class="alert alert-block alert-info">**REMEMBER:**<br>
_int1 by int2 must create a matrix to fill that size<br><br>In other words ..._<br>
- a 5 by 5 matrix will have 25 elements<br>
- a 2 by 4 matrix will have 8 elements</div>

<div class="alert alert-block alert-success">**EXERCISES:**<br>
1. print (or show) **arr**<br>
2. Get the shape of vector **arr**<br>
2. Reshape **arr** to be 1 row by 25 columns & show results<br>
3. Provide the shape of answer to 2<br>
4. Reshape **arr** as 25 rows by 1 column<br>
5. Show shape of number 4<br>
6. reshape **arr** to be 5x4</div>

<div class="alert alert-block alert-warning">**Thoughts to Ponder:**<br>
1. What did you notice different beween 2 & 4?<br>
2. What can you tell about this problem from the error in number 3?</div>

In [75]:
arr

array([-0.88241182, -0.42854637, -1.16310469, -0.63880992, -1.19410077,
       -0.6832738 , -0.68615558, -0.14458476, -1.59410106, -0.3934634 ,
       -0.19794046,  0.34840901, -1.81800176,  0.91827835,  2.57183525,
        0.2225418 ,  1.59975007, -0.49670532, -0.88890396, -1.03514511,
       -0.35399532,  0.10708129, -0.05042042, -0.42401613,  0.55496822])

In [76]:
arr.shape

(25,)

In [77]:
arr.reshape(1,25)

array([[-0.88241182, -0.42854637, -1.16310469, -0.63880992, -1.19410077,
        -0.6832738 , -0.68615558, -0.14458476, -1.59410106, -0.3934634 ,
        -0.19794046,  0.34840901, -1.81800176,  0.91827835,  2.57183525,
         0.2225418 ,  1.59975007, -0.49670532, -0.88890396, -1.03514511,
        -0.35399532,  0.10708129, -0.05042042, -0.42401613,  0.55496822]])

In [81]:
arr.reshape(1,25).shape

(1, 25)

In [80]:
arr.reshape(25,1)

array([[-0.88241182],
       [-0.42854637],
       [-1.16310469],
       [-0.63880992],
       [-1.19410077],
       [-0.6832738 ],
       [-0.68615558],
       [-0.14458476],
       [-1.59410106],
       [-0.3934634 ],
       [-0.19794046],
       [ 0.34840901],
       [-1.81800176],
       [ 0.91827835],
       [ 2.57183525],
       [ 0.2225418 ],
       [ 1.59975007],
       [-0.49670532],
       [-0.88890396],
       [-1.03514511],
       [-0.35399532],
       [ 0.10708129],
       [-0.05042042],
       [-0.42401613],
       [ 0.55496822]])

In [82]:
arr.reshape(25,1).shape

(25, 1)

In [85]:
#arr.reshape(5,5)    - Works
#arr.reshape(5,5).shape - Works

arr.reshape(5,4)  # fails

ValueError: cannot reshape array of size 25 into shape (5,4)

# Indexing & Slicing

From here we're going to go over how to select elements or groups of elements from an array.

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Assign **arr** the value returned from creating a sample array of ranged integers from [0, 11)</div>

In [89]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection

The simplest way to pick one or some elements of an array looks very similar to python lists.

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Get element 8 of **arr**<br>
2. Slice **arr** from element [1, 5)<br>
3. Slice **arr** from element [None, 4)<br>
4. Slice **arr** from element [0, 3)</div>

<div class="alert alert-block alert-info">**REMEMBER:**<br>
If you see a None somewhere in documentation, it means you can leave it **_blank_**!!!</div>

In [90]:
arr[8]

8

In [91]:
arr[1:5]

array([1, 2, 3, 4])

In [93]:
arr[None:4]

array([0, 1, 2, 3])

In [94]:
arr[:4]

array([0, 1, 2, 3])

In [95]:
arr[0:3]

array([0, 1, 2])

## Broadcasting

NumPy arrays differ from a normal Python list because of their ability to _**broadcast**_.

Basically? When you broadcast, it changes all elements to be whatever you _"broadcast"_.

`var[int1:int2]=int3`

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Make the 1st 4 elements in **arr** be 100.<br>
2. Assign **arr** the value of an array of a range of integers between 0 and up to excluding 11<br>
3. Create a slice of **arr** from 0 up to and including 5 - call it **slice_of_arr**<br>
4. Broadcast to entire **slice_of_arr** the value of (INT) 99<br>
5. Print **slice_of_arr**<br>
6. Print **arr**<br>
7. Call the **copy()** function on **arr** and assign to **arr_copy**</div>

<div class="alert alert-block alert-warning">**Thoughts To Ponder:**<br>
1. (arr == arr_copy) == True ???<br>
2. (arr is arr_copy) == True ???</div>

In [97]:
arr[:4]=100
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [100]:
arr = np.arange(0,11,1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [103]:
slice_of_arr[:]=99

In [104]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [105]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [106]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [107]:
arr == arr_copy

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [108]:
arr is arr_copy

False

In [109]:
arr is slice_of_arr

False

In [111]:
arr_copy[-1] = -1
print(arr_copy)
arr == arr_copy

[99 99 99 99 99 99  6  7  8  9 -1]


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False])

## Indexing a 2D array (Matrices)

The general format for a indexing a matrix is:

- `arr_2d[row][col]`
- `arr_2d[row,col]`

I recommend usually using the comma notation for clarity.

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Create **arr_2d** to be an array of rank 3 with 3 columns where each row is in increments of 5 starting at 5
    _**HINT:** [[5, 10, 15], ...]_<br>
2. What is row 1 of **arr_2d**?<br>
3. What is returned from **arr_2d** at row 1, column 0?<br>
4. Write number 3 a different way.<br>
5. Create a slice of **arr_2d** from first 2 rows and columns 1 until the end<br>
6. Reshape number 5 to be (1, 3)</div>

<div class="alert alert-block alert-warning">**Things To Ponder:**<br>
- What exactly happened when you called **reshape(int1, int2)**?<br>
- How to fix it?</div>

In [112]:
arr_2d = np.array([[5,10,15], [20,25,30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [115]:
#arr_2d.shape
#arr_2d.dtype
arr_2d[1]

array([20, 25, 30])

In [116]:
arr_2d[1][0]

20

In [117]:
arr_2d[1, 0]

20

In [118]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [119]:
arr_2d.reshape(1,9)

array([[ 5, 10, 15, 20, 25, 30, 35, 40, 45]])

In [120]:
arr_2d.reshape(9,1)

array([[ 5],
       [10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45]])

In [121]:
arr_2d.reshape(9)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [122]:
arr_2d.reshape(1,3)

ValueError: cannot reshape array of size 9 into shape (1,3)

## Fancy Indexing

Fancy indexing allows you to select entire rows out of order.

`some_array[[rowx, ...]]`

This will return the rows at each index within the list input.

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Assign **arr_2d** a zeros array of 10 by 10<br>
2. What is the count of row 1 in **arr_2d**? _(Trick Question!)_<br>
3. Assign to **arr_length** the answer to number 2<br>
4. For each element in range of the answer to number 2, broadcast the element _(assign the element to that row)_<br>
5. Grab rows 6, 2, 4, and 7 from **arr_2d**</div>

<div class="alert alert-block alert-warning">**Thoughts To Ponder:**<br>
- What did number 4 teach you?</div>

In [124]:
arr_2d = np.zeros((10,10))
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [130]:
#len(arr_2d[1]) # 10
# n_rows, n_cols = arr_2d.shape # 10,10

arr_2d[1].shape

(10,)

In [142]:
arr_length = arr_2d[1].shape[0]
arr_length

10

In [144]:
for i in range(arr_length):
    arr_2d[i] =  i*2

arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16., 16.],
       [18., 18., 18., 18., 18., 18., 18., 18., 18., 18.]])

In [147]:
arr_2d[:,-1:-3:-1]

array([[ 0.,  0.],
       [ 2.,  2.],
       [ 4.,  4.],
       [ 6.,  6.],
       [ 8.,  8.],
       [10., 10.],
       [12., 12.],
       [14., 14.],
       [16., 16.],
       [18., 18.]])

In [149]:
arr_2d[[6, 2, 4,  7]]

array([[12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.]])

In [151]:
arr_2d[[6, 2, 4,  7], -1:-3:-1]

array([[12., 12.],
       [ 4.,  4.],
       [ 8.,  8.],
       [14., 14.]])

In [152]:
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16., 16.],
       [18., 18., 18., 18., 18., 18., 18., 18., 18., 18.]])

In [165]:
arr_2d[[2, -3], 1::7]

array([[ 4.,  4.],
       [14., 14.]])

## Slicing

Similar to Python lists, NumPy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array.

**ACTION PLAN:**

<div class="alert alert-block alert-success">Create the following rank 2 array with shape (3, 4):</div>
<div class="alert alert-block alert-warning">[[ 1  2  3  4]<br>[ 5  6  7  8]<br>[ 9 10 11 12]]</div>

In [168]:
a= np.array([[ 1, 2, 3, 4],
             [ 5, 6, 7, 8],
             [ 9, 10, 11, 12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [169]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Slicing with indexes is just like slicing with strings or lists.
<div class="alert alert-block alert-info">a = 'I love Python'<br>b = a[7:]    # 'Python'</div>

Use slicing to:
- pull out the subarray consisting of the first 2 rows and columns 1 and 2 & assign to **b**
- ensure **b** has the following array of shape (2, 2)

In [171]:
b= a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

A slice of an array is a view into the same data, so modifying it will modify the original array.

Run these commands:
<div class="alert alert-block alert-warning">a[0, 1]<br>b[0, 0] = 77<br>a[0, 1]</div>
<div class="alert alert-block alert-info">**REMEMBER:** b[0, 0] is the same piece of data as a[0, 1]</div>

In [172]:
a[0, 1]

2

In [173]:
b[0, 0] = 77

In [174]:
a[0, 1]

77

In [178]:
a[:1,:1]= b[0, 0] = b[1, 1]
a

array([[ 7,  7,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [179]:
a[:2,:2]= b[0, 0] = b[1, 1]
a

array([[ 7,  7,  3,  4],
       [ 7,  7,  7,  8],
       [ 9, 10, 11, 12]])

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing...

Create the following rank 2 array with shape (3, 4):

<div class="alert alert-block alert-info">[[ 1  2  3  4]<br>  [ 5  6  7  8]<br>  [ 9 10 11 12]]</div>

Here is the code to run:

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Create an array of rank 3, where each rank consists of a range of 4 integers from [1:12]</div>

In [184]:
a = np.array([np.arange(1,5), np.arange(5,9), np.arange(9,13)])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

There are two ways of accessing the data in the middle row of the array.
1. Mixing integer indexing with slices yields an array of lower rank
2. Using only slices yields an array of the same rank as the original array

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Print **a** and it's shape<br>
2. Create variable row_r1 that has a rank 1 view of the 2nd row of a<br>
2. Create variable row_r2 that has rank 2 view of the 2nd row of a</div>
    
<div class="alert alert-block alert-info">**REMEMBER:**  A "rank" is the row of a matrix.</div>

<div class="alert alert-block alert-warning">**Thoughts to Ponder:**<br>
1. (row_r1 == row_r2) == True?<br>
2. (row_r1 is row_r2) == True?<br>
3. (a[1, :] is row_r1) == True?<br>
4. (row_r2 is a[1:2, :]) == True?<div>

We can make the same distinction when accessing columns of an array...

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. print **a**<br>
2. Assign **col_r1** the slice of a for all rows for column 1<br>
3. Print **col_r1** and it's shape<br>
4. Assign **col_r2** the slice of **a** for all rows between columns [1, 2)<br>
5. print **col_r2** and it's shape</div>

In other words:
- `a[:, 1]` is taking all of the rows of the first column and creating a 1 by x matrix (aka:  array)
- `a[:,1:2]` is taking all rows of the columns between 1 and up to not including 2 in order to create an x by 1 column matrix

Try this on for size:
<div class="alert alert-block alert-warning">print(a, a.shape)<br>print(a[:, 1], a[:, 1].shape)<br>print(a[:, :1], a[:, :1].shape)<br>print(a[:,2:], a[:,2:].shape)<br>print(a[:, 2:4], a[:, 2:4].shape)<br>print(a, a.shape)<br>print(a[1:,2:], a[1:,2:].shape)<div>

## Integer Array Indexing

This feature is useful when selecting or mutating a single element from each row of a matrix.

`arr_matrix[[row_x, ...], [col_a, ...]]`

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Create matrix **a** as a 3 by 2 matrix of integers from 1 up to and including 6<br>
2. Print an array of elements at (0, 0), (1, 1), and (2,0)<br>
3. Print an array of elements at (0,1) and (0,1)</div>

<div class="alert alert-class alert-warning">**Thoughts To Ponder:**<br>
Did number 3 break? Why or why not?</div>

This feature is useful when selecting or mutating a single element from each row of a matrix.

**ACTION PLAN:**
<div class="alert alert-block alert-success">
1. Reassign **a** to a 4 by 3 array of arrays from 1 up to and including 12<br>
2. Create an array **b** of 4 integers, each between [0, 3)<br>
3. Add 10 to the section of **a** where row input is a range [0, 4) and column input is **b**</div>

<div class="alert alert-class alert-warning">**Thoughts To Ponder:**<br>
What exactly did you just do?</div>

## Boolean Array Indexing (Selection)

This section will briefly go over how to use brackets for selection based off of comparison operators.

1. If you add a comparison operator to an array such as `np.arange(1, 11)` you receive a new array of booleans.

2. When you apply that array of **_bools_** to the original array you get back only the ones that are **_True_**

`some_array(some_bool)`

Frequently used to select elements of an array that satisfy some condition.

**ACTION PLAN:**
<div class="alert alert-class alert-success">
1. Create **bool_idx** and assign the value of **a > 10**<br>
2. Print the value of **a** at "index" **bool_idx**<br></div>

In [185]:
a =  np.array([np.arange(1,4), np.arange(4,7), np.arange(7,10), np.arange(10,13)])
a[]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [191]:
bool_idx =  a > 10 # what are the one that fullfill
bool_idx

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True,  True]])

In [188]:
a[bool_idx]

array([11, 12])

In [189]:
a[ a > 10] # Select them (Slice)

array([11, 12])

## The End

If you would like to learn more, please <a href='http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html'>read the documentation</a>.